### ISSUE TITLE
mappack

### ISSUE THREAD

**Issue by coyoteclan** [raphael12333/CoD1_Stuff#1]
bro upload wawa10daim maps too!!!!!

**Comment by raphael12333** [comment]
i used to get the map going here: http://eurorifles.clanwebsite.com/
but it seems the website is closed now

another way to get the map from the source might be to join the 1.5 Euro Wawa server
But i think yes we should host the map somewhere for it to be found more easily
Imo vcodmods.com would be a nice place for this, i will probably try again to get my account password reset sometimes to upload it here maybe

**Comment by coyoteclan** [comment]
Yes you should post it on vcodmods but I think you should also put the file or link to the file in GitHub repo

**Comment by raphael12333** [comment]
ok thank you for your suggestion i will think about it

**Comment by raphael12333** [comment]
@coyoteclan thanks to your suggestion the map is now uploaded on vcodmods
